version: "3"
services:
   app:
     build: 
       context: .
       dockerfile: ./Dockerfile-app
     volumes:
       - ./js:/opt/js
       - ./angie.conf:/etc/angie/angie.conf
       - ./default.conf:/etc/angie/http.d/default.conf
     ports:
       - 80:80
       - 443:443